Notification Indicator for Bookmarks
ActuallyTheSun/Vencord pull request #8
Opened 2023-09-08 14:26 UTC by nmsturcke

Add a notification indicator for bookmarks

![Xm0TW](https://github.com/ActuallyTheSun/Vencord/assets/30734036/8babaeff-a366-430d-bc35-2ade34a81efd)

2023-09-08 14:36 UTC, nmsturcke commented
As per 
![AlYCB](https://github.com/ActuallyTheSun/Vencord/assets/30734036/a9d9feba-dca3-43ce-a60c-20817e53d0e5)

2023-09-10 13:35 UTC, ActuallyTheSun requested changes
oh fuck i forgot about this sorry

2023-09-10 13:35 UTC, ActuallyTheSun commented on src/plugins/channelTabs/components/BookmarkContainer.tsx
> +        [unreadCount, mentionCount] = useStateFromStores(
this conditionally calls a hook. you'd need to either move `useStateFromStores` out of the if statement and always return 0 for folders, or move this logic to `NotificationDot`

2023-09-12 13:14 UTC, ActuallyTheSun approved these changes
thank you!

2023-09-12 13:14 UTC, merged